# Generated by Django 3.0.7 on 2020-07-05 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200705_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Persona')),
            ],
        ),
    ]
