# Generated by Django 3.0.7 on 2020-07-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_curso_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
