# Generated by Django 3.0.7 on 2020-07-11 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200705_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefono', to='core.Persona'),
        ),
    ]
